#!/bin/bash

# Verify gum is installed
if ! command -v gum &> /dev/null; then
    echo "gum is not installed. Installing..."
    if ! command -v brew &> /dev/null; then
        echo "Homebrew is not installed. Please install Homebrew first."
        exit 1
    fi
    if ! brew install gum;

    then
        echo "Failed to install gum. Please check your internet connection or try again later."
        exit 1
    fi
fi

COMMANDS="
convert-to-gif
scale-down-video
speedup-video
github-create-pull-request
github-pr-from-commit
github-pr-re-review
rename-files
brew-install-version
download-pointfree-video
"

SELECTION=$(echo "$COMMANDS" | gum choose --header "Select what to run:")
if [ -n "$SELECTION" ]; then
    print -z "$HOME/.scripts/$SELECTION "
fi
